export default {
  black: "#000",
  primaryBackground: "#1B1B1B",
  white: "#fff",
  primaryText: "#F2F2F2",
  secondaryButton: "#F6F6F6",
  border: "#EBEBED",
  label: "#B4B4B6",
  description: "#EEEEEE",
  secondaryBackground: "#8775FE",
  secondaryText: "#8775FE",
  button: "#504DB6",
  cartItem: "#ECE9FF",
  modalBackground: "#4B4B4B",
  regular: "WorkSans_400Regular",
  medium: "WorkSans_500Medium",
  semibold: "WorkSans_600SemiBold",
  bold: "WorkSans_700Bold",
};
