export default {
  black: "#000",
  primaryText: "#000",
  white: "#fff",
  primaryBackground: "#F8F8F8",
  secondaryButton: "#F6F6F6",
  border: "#EBEBED",
  label: "#B4B4B6",
  description: "#85868A",
  secondaryBackground: "#8775FE",
  secondaryText: "#8775FE",
  button: "#504DB6",
  cartItem: "#ECE9FF",
  modalBackground: "#fff",
  regular: "WorkSans_400Regular",
  medium: "WorkSans_500Medium",
  semibold: "WorkSans_600SemiBold",
  bold: "WorkSans_700Bold",
};
